// <auto-generated />
using System;
using Accounting.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accounting.WebAPI.Migrations
{
    [DbContext(typeof(AccountingContext))]
    partial class AccountingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accounting.WebAPI.Entities.Cash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CashName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RealPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RealPersonId");

                    b.ToTable("Cashes");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CashId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocNo")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CashId");

                    b.HasIndex("DocTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LookupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LookupTypeId = 1,
                            Title = "withdrawal"
                        },
                        new
                        {
                            Id = 2,
                            LookupTypeId = 1,
                            Title = "Payment"
                        },
                        new
                        {
                            Id = 3,
                            LookupTypeId = 2,
                            Title = "Iranian"
                        },
                        new
                        {
                            Id = 4,
                            LookupTypeId = 2,
                            Title = "Foreigner"
                        },
                        new
                        {
                            Id = 5,
                            LookupTypeId = 3,
                            Title = "Tehran"
                        },
                        new
                        {
                            Id = 6,
                            LookupTypeId = 3,
                            Title = "Karaj"
                        },
                        new
                        {
                            Id = 7,
                            LookupTypeId = 3,
                            Title = "Shiraz"
                        },
                        new
                        {
                            Id = 8,
                            LookupTypeId = 3,
                            Title = "Gilan"
                        });
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.LegalPerson", b =>
                {
                    b.HasBaseType("Accounting.WebAPI.Entities.Person");

                    b.Property<int>("CompanyNo")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("EconomicCode")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("RegistrationCode")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("LegalPerson");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.RealPerson", b =>
                {
                    b.HasBaseType("Accounting.WebAPI.Entities.Person");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BirthPlaceId")
                        .HasColumnType("int");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.HasIndex("BirthPlaceId");

                    b.HasIndex("NationalityId");

                    b.HasDiscriminator().HasValue("RealPerson");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Karaj",
                            Email = "tehranimohammad480",
                            PhoneNumber = "09177973283",
                            Age = 10,
                            BirthDate = new DateTime(1997, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 6,
                            FatherName = "Ali",
                            FirstName = "Mohammad Reza",
                            LastName = "Tehrani",
                            NationalCode = "0440799996",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 2,
                            Address = "Tehran",
                            Email = "tehraniAli480",
                            PhoneNumber = "09171619993",
                            Age = 20,
                            BirthDate = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 5,
                            FatherName = "Kamal",
                            FirstName = "Ali",
                            LastName = "Tehrani",
                            NationalCode = "1234567890",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 3,
                            Address = "Abadan",
                            Email = "sdlksdkvnksnv",
                            PhoneNumber = "09174856699",
                            Age = 15,
                            BirthDate = new DateTime(1997, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 5,
                            FatherName = "Ali",
                            FirstName = "Reza",
                            LastName = "Bogari",
                            NationalCode = "0440799996",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tehran",
                            Email = "tehraniAli480",
                            PhoneNumber = "01478747879",
                            Age = 47,
                            BirthDate = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 6,
                            FatherName = "Kamal",
                            FirstName = "Mahyar",
                            LastName = "Bogari",
                            NationalCode = "2546845865",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "Karaj",
                            Email = "tehranimohammad480",
                            PhoneNumber = "01478954789",
                            Age = 14,
                            BirthDate = new DateTime(1997, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 7,
                            FatherName = "Ali",
                            FirstName = "Mohammad Reza",
                            LastName = "Tehrani",
                            NationalCode = "147569874",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 6,
                            Address = "Tehran",
                            Email = "rggrg",
                            PhoneNumber = "01236987474",
                            Age = 12,
                            BirthDate = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 8,
                            FatherName = "Kamal",
                            FirstName = "Ali",
                            LastName = "Tehrani",
                            NationalCode = "9898989745",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 7,
                            Address = "Karaj",
                            Email = "tehranimohammad480",
                            PhoneNumber = "01478745454",
                            Age = 45,
                            BirthDate = new DateTime(1997, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 5,
                            FatherName = "Ali",
                            FirstName = "Ahmad Reza",
                            LastName = "Tehrani",
                            NationalCode = "4565654568",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 8,
                            Address = "Tehran",
                            Email = "tehraniAli480",
                            PhoneNumber = "09171619993",
                            Age = 20,
                            BirthDate = new DateTime(1985, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 6,
                            FatherName = "Kamal",
                            FirstName = "Ali",
                            LastName = "Tehrani",
                            NationalCode = "1234567890",
                            NationalityId = 3
                        },
                        new
                        {
                            Id = 9,
                            Address = "Karaj",
                            Email = "djjfgodf",
                            PhoneNumber = "01478954758",
                            Age = 25,
                            BirthDate = new DateTime(1788, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 7,
                            FatherName = "Parsa",
                            FirstName = "Mohammad Ali",
                            LastName = "Tehrani",
                            NationalCode = "1578947524",
                            NationalityId = 4
                        },
                        new
                        {
                            Id = 10,
                            Address = "Tehran",
                            Email = "tehraniAli480",
                            PhoneNumber = "09171619993",
                            Age = 16,
                            BirthDate = new DateTime(1975, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthPlaceId = 8,
                            FatherName = "Akbar",
                            FirstName = "Asghar",
                            LastName = "Bogari",
                            NationalCode = "1475369514",
                            NationalityId = 4
                        });
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Cash", b =>
                {
                    b.HasOne("Accounting.WebAPI.Entities.RealPerson", "Cashier")
                        .WithMany("Cashes")
                        .HasForeignKey("RealPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Document", b =>
                {
                    b.HasOne("Accounting.WebAPI.Entities.Cash", "Cash")
                        .WithMany("Documents")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Accounting.WebAPI.Entities.Lookup", "DocType")
                        .WithMany("Documents")
                        .HasForeignKey("DocTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Accounting.WebAPI.Entities.Person", "AccountSide")
                        .WithMany("Documents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccountSide");

                    b.Navigation("Cash");

                    b.Navigation("DocType");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.RealPerson", b =>
                {
                    b.HasOne("Accounting.WebAPI.Entities.Lookup", "BirthPlace")
                        .WithMany("RealPeople")
                        .HasForeignKey("BirthPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.WebAPI.Entities.Lookup", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BirthPlace");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Cash", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Lookup", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RealPeople");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.Person", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Accounting.WebAPI.Entities.RealPerson", b =>
                {
                    b.Navigation("Cashes");
                });
#pragma warning restore 612, 618
        }
    }
}
